const SET_USERID = "SET_USERID";

const SEND_MESSAGE = "SEND_MESSAGE";

const BROADCAST = "BROADCAST";

const GET_CONNECTED_USERS = "GET_CONNECTED_USERS";

const GET_USERS = "GET_USERS";

module.exports = { SET_USERID, SEND_MESSAGE, BROADCAST, GET_CONNECTED_USERS, GET_USERS }