const SET_USERID = "SET_USERID";

const SEND_MESSAGE = "SEND_MESSAGE";

const BROADCAST = "BROADCAST";

const GET_CONNECTED_USERS = "GET_CONNECTED_USERS";

const GET_USERS = "GET_USERS";

const NEW_CONNECTION = "NEW_CONNECTION";

const USER_DISCONNECTION = "USER_DISCONNECTION";

//Subscriptions
const SUBSCRIBE_TO_USERS = "SUBSCRIBE_TO_USERS";

const UN_SUBSCRIBE_TO_USERS = "UN_SUBSCRIBE_TO_USERS";

const SUBSCRIBE = "SUBSCRIBE";

const UNSUBSCRIBE = "UNSUBSCRIBE";

module.exports = { SET_USERID, SEND_MESSAGE, BROADCAST, GET_CONNECTED_USERS, GET_USERS, NEW_CONNECTION, USER_DISCONNECTION, SUBSCRIBE_TO_USERS, UN_SUBSCRIBE_TO_USERS }